### ISSUE TITLE
Local setup

### ISSUE THREAD

**Issue by joshstrange** [hashedin/squealy#222]
Really would love instructions on how to setup this up locally. Deploy to Heroku is cool but there is no way I can access our databases publically (for good reason). I've tried to do it on my own but I keep getting errors when trying to run the Procfile with honcho about "OperationalError: no such table: djcelery_periodictask" and it's not clear if I need to setup a different database for SQueLy or if it uses something like sqlite for it's config.

What I've already done:

* Installed Honcho to run the procfile
* `pip install -r requirements.txt`
* `npm install` in web directory
* `mvn install`
* `honcho start`

And I get:

````
08:22:48 system   | worker.1 started (pid=30839)
08:22:48 system   | web.1 started (pid=30840)
08:22:49 web.1    | [2017-05-11 08:22:49 -0400] [30840] [INFO] Starting gunicorn 19.6.0
08:22:49 web.1    | [2017-05-11 08:22:49 -0400] [30840] [INFO] Listening at: http://0.0.0.0:5000 (30840)
08:22:49 web.1    | [2017-05-11 08:22:49 -0400] [30840] [INFO] Using worker: sync
08:22:49 web.1    | [2017-05-11 08:22:49 -0400] [30843] [INFO] Booting worker with pid: 30843
08:22:50 worker.1 | [2017-05-11 12:22:50,312: INFO/Beat] beat: Starting...
08:22:50 worker.1 | [2017-05-11 12:22:50,317: INFO/Beat] Writing entries (0)...
08:22:50 worker.1 | [2017-05-11 12:22:50,317: INFO/MainProcess] Connected to django://localhost//
08:22:50 worker.1 | [2017-05-11 12:22:50,332: INFO/Beat] Writing entries (0)...
08:22:50 worker.1 | [2017-05-11 12:22:50,332: ERROR/Beat] Process Beat
08:22:50 worker.1 | Traceback (most recent call last):
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/billiard/process.py", line 292, in _bootstrap
08:22:50 worker.1 |     self.run()
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 553, in run
08:22:50 worker.1 |     self.service.start(embedded_process=True)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 470, in start
08:22:50 worker.1 |     humanize_seconds(self.scheduler.max_interval))
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 325, in __get__
08:22:50 worker.1 |     value = obj.__dict__[self.__name__] = self.__get(obj)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 512, in scheduler
08:22:50 worker.1 |     return self.get_scheduler()
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 507, in get_scheduler
08:22:50 worker.1 |     lazy=lazy)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/utils/imports.py", line 53, in instantiate
08:22:50 worker.1 |     return symbol_by_name(name)(*args, **kwargs)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/djcelery/schedulers.py", line 152, in __init__
08:22:50 worker.1 |     Scheduler.__init__(self, *args, **kwargs)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 185, in __init__
08:22:50 worker.1 |     self.setup_schedule()
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/djcelery/schedulers.py", line 159, in setup_schedule
08:22:50 worker.1 |     self.install_default_entries(self.schedule)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/djcelery/schedulers.py", line 254, in schedule
08:22:50 worker.1 |     self._schedule = self.all_as_schedule()
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/djcelery/schedulers.py", line 165, in all_as_schedule
08:22:50 worker.1 |     for model in self.Model.objects.enabled():
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 256, in __iter__
08:22:50 worker.1 |     self._fetch_all()
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
08:22:50 worker.1 |     self._result_cache = list(self.iterator())
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
08:22:50 worker.1 |     results = compiler.execute_sql()
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
08:22:50 worker.1 |     cursor.execute(sql, params)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
08:22:50 worker.1 |     return super(CursorDebugWrapper, self).execute(sql, params)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
08:22:50 worker.1 |     return self.cursor.execute(sql, params)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
08:22:50 worker.1 |     six.reraise(dj_exc_type, dj_exc_value, traceback)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
08:22:50 worker.1 |     return self.cursor.execute(sql, params)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
08:22:50 worker.1 |     return Database.Cursor.execute(self, query, params)
08:22:50 worker.1 | OperationalError: no such table: djcelery_periodictask
08:22:50 worker.1 | [2017-05-11 12:22:50,335: ERROR/MainProcess] Unrecoverable error: OperationalError('no such table: djkombu_queue',)
08:22:50 worker.1 | Traceback (most recent call last):
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
08:22:50 worker.1 |     self.blueprint.start(self)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
08:22:50 worker.1 |     step.start(parent)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
08:22:50 worker.1 |     return self.obj.start()
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 280, in start
08:22:50 worker.1 |     blueprint.start(self)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
08:22:50 worker.1 |     step.start(parent)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 655, in start
08:22:50 worker.1 |     c.connection, on_decode_error=c.on_decode_error,
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/celery/app/amqp.py", line 385, in __init__
08:22:50 worker.1 |     **kw
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 364, in __init__
08:22:50 worker.1 |     self.revive(self.channel)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 376, in revive
08:22:50 worker.1 |     self.declare()
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 386, in declare
08:22:50 worker.1 |     queue.declare()
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/kombu/entity.py", line 522, in declare
08:22:50 worker.1 |     self.queue_declare(nowait, passive=False)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/kombu/entity.py", line 548, in queue_declare
08:22:50 worker.1 |     nowait=nowait)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 446, in queue_declare
08:22:50 worker.1 |     self._new_queue(queue, **kwargs)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/kombu/transport/django/__init__.py", line 36, in _new_queue
08:22:50 worker.1 |     self.Queue.objects.get_or_create(name=queue)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
08:22:50 worker.1 |     return getattr(self.get_queryset(), name)(*args, **kwargs)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 473, in get_or_create
08:22:50 worker.1 |     return self.get(**lookup), False
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 379, in get
08:22:50 worker.1 |     num = len(clone)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in __len__
08:22:50 worker.1 |     self._fetch_all()
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
08:22:50 worker.1 |     self._result_cache = list(self.iterator())
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
08:22:50 worker.1 |     results = compiler.execute_sql()
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
08:22:50 worker.1 |     cursor.execute(sql, params)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
08:22:50 worker.1 |     return super(CursorDebugWrapper, self).execute(sql, params)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
08:22:50 worker.1 |     return self.cursor.execute(sql, params)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
08:22:50 worker.1 |     six.reraise(dj_exc_type, dj_exc_value, traceback)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
08:22:50 worker.1 |     return self.cursor.execute(sql, params)
08:22:50 worker.1 |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
08:22:50 worker.1 |     return Database.Cursor.execute(self, query, params)
08:22:50 worker.1 | OperationalError: no such table: djkombu_queue
08:22:51 worker.1 | [2017-05-11 12:22:51,102: INFO/MainProcess] beat: Shutting down...
08:22:51 worker.1 |
08:22:51 worker.1 |  -------------- celery@joshbook.local v3.1.25 (Cipater)
08:22:51 worker.1 | ---- **** -----
08:22:51 worker.1 | --- * ***  * -- Darwin-16.5.0-x86_64-i386-64bit
08:22:51 worker.1 | -- * - **** ---
08:22:51 worker.1 | - ** ---------- [config]
08:22:51 worker.1 | - ** ---------- .> app:         squealyproj:0x10d9a6e50
08:22:51 worker.1 | - ** ---------- .> transport:   django://localhost//
08:22:51 worker.1 | - ** ---------- .> results:
08:22:51 worker.1 | - *** --- * --- .> concurrency: 4 (prefork)
08:22:51 worker.1 | -- ******* ----
08:22:51 worker.1 | --- ***** ----- [queues]
08:22:51 worker.1 |  -------------- .> celery           exchange=celery(direct) key=celery
08:22:51 worker.1 |
08:22:51 worker.1 |
08:22:51 worker.1 | [tasks]
08:22:51 worker.1 |   . squealy.tasks.trigger_emails
08:22:51 worker.1 |
08:22:51 system   | worker.1 stopped (rc=0)
08:22:51 system   | sending SIGTERM to web.1 (pid 30840)
08:22:51 web.1    | [2017-05-11 12:22:51 +0000] [30843] [INFO] Worker exiting (pid: 30843)
08:22:51 web.1    | [2017-05-11 08:22:51 -0400] [30840] [INFO] Handling signal: term
08:22:51 web.1    | [2017-05-11 08:22:51 -0400] [30840] [INFO] Shutting down: Master
08:22:51 system   | web.1 stopped (rc=0)
````

**Comment by swapnil95** [comment]
Can you try following these instructions - https://github.com/hashedin/squealy#development

**Comment by joshstrange** [comment]
Didn't see that, trying now, thanks

**Comment by devashishsharma2302** [comment]
Did it work out?

**Comment by mkalioby** [comment]
Yes it did for me
