### ISSUE TITLE
One click "Deploy to Heroku" build failed

### ISSUE THREAD

**Issue by tazmaniax** [hashedin/squealy#229]
Hi, I just tried the one click "Deploy to Heroku" and the build failed, specially with the Python setup. Do you know what would have caused this? thx, Chris

<img width="575" alt="screenshot 2017-06-21 20 41 24" src="https://user-images.githubusercontent.com/1079943/27403394-275116ba-56c2-11e7-8f55-a4a0a1770f31.png">

```
-----> Python app detected
-----> Installing python-3.6.1
-----> Installing pip
-----> Installing requirements with pip
       Collecting coverage==4.0.3 (from -r /tmp/build_7c40d47a41e0aebbb956891a11093973/hashedin-squealy-1e32dcc/requirements.txt (line 1))
         Downloading coverage-4.0.3.tar.gz (354kB)
       Collecting Django==1.10.2 (from -r /tmp/build_7c40d47a41e0aebbb956891a11093973/hashedin-squealy-1e32dcc/requirements.txt (line 2))
         Downloading Django-1.10.2-py2.py3-none-any.whl (6.8MB)
       Collecting django-celery==3.2.1 (from -r /tmp/build_7c40d47a41e0aebbb956891a11093973/hashedin-squealy-1e32dcc/requirements.txt (line 3))
         Downloading django-celery-3.2.1.tar.gz (91kB)
       Collecting djangorestframework==3.5.1 (from -r /tmp/build_7c40d47a41e0aebbb956891a11093973/hashedin-squealy-1e32dcc/requirements.txt (line 4))
         Downloading djangorestframework-3.5.1-py2.py3-none-any.whl (708kB)
       Collecting django-nose==1.4.4 (from -r /tmp/build_7c40d47a41e0aebbb956891a11093973/hashedin-squealy-1e32dcc/requirements.txt (line 5))
         Downloading django_nose-1.4.4-py2.py3-none-any.whl
       Collecting jinjasql==0.1.4 (from -r /tmp/build_7c40d47a41e0aebbb956891a11093973/hashedin-squealy-1e32dcc/requirements.txt (line 6))
         Downloading jinjasql-0.1.4.tar.gz
       Collecting django-cors-headers==1.2.2 (from -r /tmp/build_7c40d47a41e0aebbb956891a11093973/hashedin-squealy-1e32dcc/requirements.txt (line 7))
         Downloading django_cors_headers-1.2.2-py2.py3-none-any.whl
       Collecting arrow==0.8.0 (from -r /tmp/build_7c40d47a41e0aebbb956891a11093973/hashedin-squealy-1e32dcc/requirements.txt (line 8))
         Downloading arrow-0.8.0.tar.gz (81kB)
       Collecting psycopg2==2.6.2 (from -r /tmp/build_7c40d47a41e0aebbb956891a11093973/hashedin-squealy-1e32dcc/requirements.txt (line 9))
         Downloading psycopg2-2.6.2.tar.gz (376kB)
       Collecting dj-database-url==0.4.2 (from -r /tmp/build_7c40d47a41e0aebbb956891a11093973/hashedin-squealy-1e32dcc/requirements.txt (line 10))
         Downloading dj_database_url-0.4.2-py2.py3-none-any.whl
       Collecting MySQL-python==1.2.5 (from -r /tmp/build_7c40d47a41e0aebbb956891a11093973/hashedin-squealy-1e32dcc/requirements.txt (line 11))
         Downloading MySQL-python-1.2.5.zip (108kB)
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-5nuuo6oc/MySQL-python/setup.py", line 13, in <module>
               from setup_posix import get_config
             File "/tmp/pip-build-5nuuo6oc/MySQL-python/setup_posix.py", line 2, in <module>
               from ConfigParser import SafeConfigParser
           ModuleNotFoundError: No module named 'ConfigParser'
           
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5nuuo6oc/MySQL-python/
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by swapnil95** [comment]
Can you please try with python 2.7. Squealy does not support python 3 yet. We will update this in the readme

**Comment by devashishsharma2302** [comment]
Hi tazmaniax, 
This issue is arising due to a recent change made by Heroku on 20th June, 2017 that changes default python runtime to 3.6.1 instead of 2.7.13. [https://devcenter.heroku.com/changelog-items/1169](https://devcenter.heroku.com/changelog-items/1169).

I will update and fix it surely. Thanks for showing interest in the project.

**Comment by devashishsharma2302** [comment]
FIXED.

**Comment by hellofwdadmin** [comment]
@devashishsharma2302 awesome, thx! This sounds like a great tool and I'm very excited to see what it can do.

**Comment by virgincodes** [comment]
what happened here like seriously where and what is the Fix

**Comment by devashishsharma2302** [comment]
@virgincodes This was caused due to the default postgres version changed by Heroku to 10. The issue is fixed now by updating related library versions. Thank you for reporting.

**Comment by virgincodes** [comment]
no need just changed dependencies
